#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libdmx
Version  : 1.1.5
Release  : 17
URL      : https://www.x.org/releases/individual/lib/libdmx-1.1.5.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libdmx-1.1.5.tar.gz
Source1  : https://www.x.org/releases/individual/lib/libdmx-1.1.5.tar.gz.sig
Summary  : The dmx Library
Group    : Development/Tools
License  : MIT
Requires: libdmx-lib = %{version}-%{release}
Requires: libdmx-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : libX11-dev
BuildRequires : libX11-lib
BuildRequires : pkgconfig(dmxproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libdmx - X Window System DMX (Distributed Multihead X) extension library
-------------------------------------------------------------------------

%package dev
Summary: dev components for the libdmx package.
Group: Development
Requires: libdmx-lib = %{version}-%{release}
Provides: libdmx-devel = %{version}-%{release}
Requires: libdmx = %{version}-%{release}

%description dev
dev components for the libdmx package.


%package lib
Summary: lib components for the libdmx package.
Group: Libraries
Requires: libdmx-license = %{version}-%{release}

%description lib
lib components for the libdmx package.


%package license
Summary: license components for the libdmx package.
Group: Default

%description license
license components for the libdmx package.


%prep
%setup -q -n libdmx-1.1.5
cd %{_builddir}/libdmx-1.1.5
pushd ..
cp -a libdmx-1.1.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685983086
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1685983086
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libdmx
cp %{_builddir}/libdmx-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libdmx/6c394114eefb35de30b9675a99cc1500c6e574cb || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/dmxext.h
/usr/lib64/libdmx.so
/usr/lib64/pkgconfig/dmx.pc
/usr/share/man/man3/DMX.3
/usr/share/man/man3/DMXAddInput.3
/usr/share/man/man3/DMXAddScreen.3
/usr/share/man/man3/DMXChangeDesktopAttributes.3
/usr/share/man/man3/DMXChangeScreensAttributes.3
/usr/share/man/man3/DMXForceWindowCreation.3
/usr/share/man/man3/DMXGetDesktopAttributes.3
/usr/share/man/man3/DMXGetInputAttributes.3
/usr/share/man/man3/DMXGetInputCount.3
/usr/share/man/man3/DMXGetScreenAttributes.3
/usr/share/man/man3/DMXGetScreenCount.3
/usr/share/man/man3/DMXGetWindowAttributes.3
/usr/share/man/man3/DMXQueryExtension.3
/usr/share/man/man3/DMXQueryVersion.3
/usr/share/man/man3/DMXRemoveInput.3
/usr/share/man/man3/DMXRemoveScreen.3
/usr/share/man/man3/DMXSync.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libdmx.so.1.0.0
/usr/lib64/libdmx.so.1
/usr/lib64/libdmx.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libdmx/6c394114eefb35de30b9675a99cc1500c6e574cb
