#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libdmx
Version  : 1.1.3
Release  : 7
URL      : http://xorg.freedesktop.org/releases/individual/lib/libdmx-1.1.3.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libdmx-1.1.3.tar.gz
Summary  : The dmx Library
Group    : Development/Tools
License  : MIT
Requires: libdmx-lib
Requires: libdmx-doc
BuildRequires : pkgconfig(dmxproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)

%description
libdmx - X Window System DMX (Distributed Multihead X) extension library
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libdmx package.
Group: Development
Requires: libdmx-lib

%description dev
dev components for the libdmx package.


%package doc
Summary: doc components for the libdmx package.
Group: Documentation

%description doc
doc components for the libdmx package.


%package lib
Summary: lib components for the libdmx package.
Group: Libraries

%description lib
lib components for the libdmx package.


%prep
%setup -q -n libdmx-1.1.3

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/dmxext.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
